FROM tensorflow/tensorflow:2.4.3-jupyter

# Install git
RUN apt update && \
         apt-get install -y git && \
          /usr/local/bin/python -m pip install --upgrade pip && \
          pip install atom

RUN mkdir -p ~/atom/{download_catalogue,code_directory,model_directory,public}
CMD atom